import Head from 'next/head'
import ShowGroupResult from '../components/ShowGroupResult'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Notes PHP | 2021-2022</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="bg-gray-100">
        <div className="pb-6">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
            <ShowGroupResult group="y1" />
            <ShowGroupResult group="y2" />
          </div>
        </div>
      </main>
    </div>
  )
}
